import './pagination'
// import './logo'
import './makeButtonsLink'
import './positionBurger'
import './menu'
// import './forVideo'
import './removePlugin'
// import './scrollTo'
import './savePositionOnResize'